# constants.py
TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767
MIN_AMOUNT = 1
MAX_AMOUNT = 32767
TEXT_TRUNCATION = 20
