version: '3.8'

volumes:
  pg_data:
  static:
  media:

networks:
  foodgram_network:
    driver: bridge

services:
  db:
    container_name: foodgram_db
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - foodgram_network

  backend:
    container_name: foodgram_backend
    image: dmitrievigor/foodgram_backend:latest
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - static:/app/static/backend/
      - media:/app/media/
    restart: always
    networks:
      - foodgram_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - foodgram_network

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - /home/yc-user/foodgram/infra/nginx.conf:/etc/nginx/conf.d/default.conf   
      - ../frontend/build:/usr/share/nginx/html/
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - foodgram_network