version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: always

  backend:
    build: ../backend
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.25.4-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/app/static
      - media:/app/media

    depends_on:
      - backend
      - frontend

    restart: always
