# Generated by Django 3.2.3 on 2025-04-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250429_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
