# Generated by Django 4.2.7 on 2025-04-09 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Время не может быть менее одной минуты!')], verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
